<a href="https://colab.research.google.com/github/lalitbhattarai/Pytorch_Fundamentals/blob/main/Pytorch_Fundamentals_class_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.5.1+cu124


##INTRODUCTION TO TENSORS
**CREATING A TENSOR**

In [ ]:
#SCALAR
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#VECTOR
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX=torch.tensor([[7,8],
                    [1,3]])
MATRIX

tensor([[7, 8],
        [1, 3]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSORS
TENSOR=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#RANDOM TENSORS
#creating a randomtensor of (3,4)

random_tensors=torch.rand(3,4,)
random_tensors

tensor([[0.1084, 0.1363, 0.4837, 0.0277],
        [0.4188, 0.1618, 0.7325, 0.7151],
        [0.1854, 0.9740, 0.8991, 0.1894]])

In [ ]:
random_tensors.ndim

2

In [ ]:
#creating a random tensor with simiar shape to an image tensors
random_image_size_tensor=torch.rand(size=(224,224,3)) #These are the height weight and colourof the images
random_image_size_tensor

tensor([[[0.6729, 0.8664, 0.2262],
         [0.5145, 0.9024, 0.9862],
         [0.7562, 0.7823, 0.1329],
         ...,
         [0.4488, 0.5823, 0.9520],
         [0.2116, 0.4714, 0.8018],
         [0.9420, 0.4557, 0.9539]],

        [[0.5717, 0.9083, 0.8037],
         [0.8261, 0.6053, 0.8425],
         [0.6864, 0.6980, 0.2233],
         ...,
         [0.2254, 0.6203, 0.8651],
         [0.0354, 0.3106, 0.2566],
         [0.2375, 0.1654, 0.8174]],

        [[0.0733, 0.9022, 0.4643],
         [0.5618, 0.9423, 0.9541],
         [0.8261, 0.0274, 0.5004],
         ...,
         [0.1250, 0.9324, 0.8875],
         [0.8627, 0.5297, 0.7349],
         [0.8253, 0.5567, 0.0326]],

        ...,

        [[0.3004, 0.0100, 0.3944],
         [0.0414, 0.3968, 0.7089],
         [0.6107, 0.6063, 0.5495],
         ...,
         [0.9812, 0.5883, 0.2937],
         [0.3452, 0.5781, 0.2645],
         [0.0634, 0.9454, 0.4159]],

        [[0.7988, 0.1761, 0.6135],
         [0.1283, 0.5863, 0.8773],
         [0.

In [ ]:
random_image_size_tensor.ndim

3

In [ ]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [ ]:
#creating a tenspr of all zeros
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
#creating a tensors of the certain range
one_to_range=torch.arange(start=0,end=10,step=1)
one_to_range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#craeting tensor like
ten_zeros=torch.zeros_like(input=one_to_range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##Tenosrs data types

In [ ]:
#float 32 tensrs
float_32_tensors=torch.tensor([3.0,6.0,9.0],dtype=None,device=None)
float_32_tensors

tensor([3., 6., 9.])

In [ ]:
float_32_tensors.dtype

torch.float32

In [ ]:
#changing float 32datatype into float 16 datatype
float_16_datatype=float_32_tensors.type(torch.float16)
float_16_datatype

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_datatype.dtype

torch.float16

In [ ]:
float_16_datatype*float_32_tensors

tensor([ 9., 36., 81.])

In [ ]:
inrt_32_tensor=torch.tensor([2,3,4],dtype=torch.int32)
inrt_32_tensor

tensor([2, 3, 4], dtype=torch.int32)

##Getting informaon from tensors
1.Tensors not right dataype--ti do get datatype from a tensor can use tensor.dtype
2--Tensors not right shape--to get shape form the tensor can ue tensor.shape
3.Tensors not no the right device--To get device from a tensor ,can use tensor.device

In [ ]:
#Creating a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.4071, 0.5625, 0.4482, 0.9300],
        [0.4217, 0.7052, 0.4723, 0.7564],
        [0.1757, 0.6134, 0.8260, 0.9781]])

In [ ]:
#find out details about some_tensor
print(some_tensor)
print(f"Datatype of the tensor :{some_tensor.dtype}")
print(f"Shape of the tensor is : {some_tensor.shape}")
print(f"Device in ehich the tensor is on :{some_tensor.device}")

tensor([[0.4071, 0.5625, 0.4482, 0.9300],
        [0.4217, 0.7052, 0.4723, 0.7564],
        [0.1757, 0.6134, 0.8260, 0.9781]])
Datatype of the tensor :torch.float32
Shape of the tensor is : torch.Size([3, 4])
Device in ehich the tensor is on :cpu


##Manupalation of the tensors(tensor operation)
Tensor operation includes
1.Addition
2.Subtraction
3.multiplication (element wise)
4.Division
5.Matrix multiplications


In [ ]:
#cretae a tensor
tenor=torch.tensor([1,2,3])
tenor=tenor+100

In [ ]:
#multiply the tensor
tenor*10


tensor([1010, 1020, 1030])

In [ ]:
tenor

tensor([101, 102, 103])

In [ ]:
#Subtraction
tenor-10

tensor([91, 92, 93])

In [ ]:
#try out pytorch inbuild function
torch.mul(tenor,10)

tensor([1010, 1020, 1030])

In [ ]:
torch.add(tenor,10)

tensor([111, 112, 113])

#MATRIX multiplication
Two main way of perforn multiplication in neural network and deep learning:
1.Element _wise multiplication
2.Matrix multiplication(dit product)

There are two rules that perform matrix multiplication need to satisfy
1)the inner dimension must match
   ...(3,2) @ (3,2) .wont work
   ...


In [ ]:
#Element wise multiplications
a=torch.tensor([2,3,4])
b=torch.tensor([5,6,7])
print(a,b)
print(f"The multipliacation of two tensors are :{a*b}")


tensor([2, 3, 4]) tensor([5, 6, 7])
The multipliacation of two tensors are :tensor([10, 18, 28])


In [ ]:
#MATRIX multiplication
torch.matmul(a,b)

tensor(56)

One of the most common errors in deeep learninh

In [ ]:
#shapes for matrix multiplication
a=torch.tensor([[1,2],
                [3,4],
                [5,6]])
b=torch.tensor([[7,10],
                [8,11],
                [9,12]])

multipl=torch.matmul(a,b.T)  # we can use mm insted of matmul both are same things

print(multipl)



tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [ ]:
a.shape,b.shape


(torch.Size([3, 2]), torch.Size([3, 2]))

TO FIXED OUT TENSOR FIXED ISSUE WE CAN MANUPLATE THE SHAPE FO ONE OF OUR TENSORD

A transpose switches the axes or dimension of a given tensor


In [ ]:
b.T,b.T.size()

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
#the matrix multiplication Operation works when tensor B is transpose that mean changed
print(f"Original size of tensor A is :{a.shape} and Orginal shape of tensor B is :{b.shape}")
print(f"New shape of tensor a is same that is {a.shape} but the shape of the tensor b is changed now b is {b.T.shape}")
print("output:\n")
output=torch.matmul(a,b.T)
print(output)
print(f"\n  Output shape is : {output.shape}")



Original size of tensor A is :torch.Size([3, 2]) and Orginal shape of tensor B is :torch.Size([3, 2])
New shape of tensor a is same that is torch.Size([3, 2]) but the shape of the tensor b is changed now b is torch.Size([2, 3])
output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

  Output shape is : torch.Size([3, 3])


 The main rule for marix multiplication is inner dimension of two matrix must match for
 matrix multiplication