<a href="https://colab.research.google.com/github/lalitbhattarai/Pytorch_Fundamentals/blob/main/Pytorch_Fundamentals_class_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Finding the min,Max,Mean,Sum,etc(Tensor aggregation)

In [1]:
import torch

In [2]:
#Create a tensor
x=torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [3]:
#find the min
torch.min(x),x.min()


(tensor(1), tensor(1))

In [4]:
#find the max
torch.max(x),x.max()

(tensor(91), tensor(91))

In [5]:
#Find the mean In the tensors -Torch.mean requires that is dtype of flaot32
torch.mean(x.type(torch.float32))



tensor(46.)

In [6]:
y=x.type(torch.float32).mean()
y


tensor(46.)

In [7]:
y.dtype

torch.float32

In [8]:
torch.sum(x),x.sum()

(tensor(460), tensor(460))

##Finding the positional min and max

In [9]:
#minding the minumun valu eand its index
x.argmin()

tensor(0)

In [10]:
x[0]

tensor(1)

In [11]:
#this is finding the index of maximum number availablein the tensor and its value
x.argmax()

tensor(9)

In [12]:
x[9]

tensor(91)

In [13]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

Reshaping,staking ,squezzing,and unsquezzing tensor
*Reshaping--Reshape an input tensor to a define ShapeType
*View--return  a view of an input of certaing shape but  keep the same meanory as
the orginal
**Staking--combaining multiple tensors on top of eah oher (vstack )and side by side hstack
**Squeeze--remove all the  1 dimension from the tensor
**unsqueeze--add a 1 dimensions dfrom a tensor
**permute--Return a view of the input with dimension (swapped )in a certain way

In [14]:
#let's Create a tensor
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [15]:
#add an extra deminsion
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.size()

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [16]:
#Change the view
z=x.view(1,9)
z,z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [17]:
#changing Z changes x(Because a view of the tensor share the same memory as the original tensor)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [18]:
#stack tensor in top of each other
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked


tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [19]:
#Torch.squeeze-to remaove the single dims form target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [20]:
x_reshaped.shape

torch.Size([1, 9])

In [21]:
x_squeeze=x_reshaped.squeeze()
x_squeeze

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
#Torch.unsqueeze-add the single dime to a target tensor at the specific dims
print(f"Previous target: {x_squeeze}")
print(f"Previous shape: {x_squeeze.shape}")
#Adding an extra dimension with unsqueeze
x_unsqueezed=x_squeeze.unsqueeze(dim=0)
print(f"\n New Tensor: {x_unsqueezed}")
print(f"new Shape:{x_unsqueezed.shape}")



Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

 New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
new Shape:torch.Size([1, 9])


In [23]:
#trrch.permute-rearrange the dimension of the target random numbers
x_original=torch.rand(size=(224,224,3))  #(height,width,colour_channels(red green and blue))
#premute the original tensor to rearrang the axis (or dim) order.
x_permuted=x_original.permute(2,0,1) #shifts axis 0->1,1->2,2->0
print(f"Previous shape: {x_original.shape}")
print(f"Premuted shape: {x_permuted.shape}")# 9colour channel,height,width

Previous shape: torch.Size([224, 224, 3])
Premuted shape: torch.Size([3, 224, 224])


In [24]:
x_original[1,0,0]=9.1234

In [25]:
x_original[1,0,0],x_permuted[1,0,0]

(tensor(9.1234), tensor(0.2426))

##Indexing (select data from tensor)

Indexing with pytorch is similar to indexing with numpy

In [26]:
#create a tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [27]:
#lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [28]:
#Let's index the middle bracket(dim=1)
x[0,0]

tensor([1, 2, 3])

In [29]:
#let's index on he most inner bracket(last dimension)
x[0,2,2]

tensor(9)

In [30]:
#you can also use ":" to select "all" os a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [31]:
#Get all values of 0th and 1st deminsion but the index 1 nad 2 deiension
x[:,:,1]

tensor([[2, 5, 8]])

In [32]:
x[:,1,1]

tensor([5])

In [33]:
#get index of 0 dimension and 1st dimension and all values od 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [34]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [35]:
#index on x return 9
x[:,2,2]

tensor([9])

In [36]:
#index on x return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

from ctypes import LibraryLoader
##Pytorch tensors and NumPy
NumPy is a popular scientific Python numeric computing computing LibraryLoader

And because of this .pytorch has functionality to ineract with it

*Dtata is NumPy  ,want in Pytorch tensor->`torch.from_numpy(ndarray)

.Pytorch Tesor ->NumPy ->torch.tensor.numpy()

In [37]:
#NumPy array to tensor
import torch
import numpy as np

array=np.arange(1.0 ,8.0)
tensor=torch.from_numpy(array) #when you convert the numpy datatype to pytorch datatype the dtype is numpay defult that is float 64
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [38]:
array.dtype

dtype('float64')

In [39]:
tensor.dtype

torch.float64

In [40]:
#change the value of the array
array=array+1
array,tensor


(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [41]:
#Tensor to Numpy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [42]:
numpy_tensor.dtype

dtype('float32')

In [43]:
tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

from typing_extensions import LiteralString
##Reproducibility (Triying to take random out of random)

In Short How a neural network LiteralString

`start with random numbers -.Tenosr operation->Update random numbers to try and make them better Representations  
of the data-.again->again

To reduce the randomness in neural network and Pytorch comes the concept of a Random seed

Essentially what the random seed does in "flavour the randmoness

In [47]:
import torch
#create two random tensors

random_tensor_a=torch.rand(3,4)
random_tensor_b=torch.rand(3,4)
print(random_tensor_a)
print(random_tensor_b)

print(random_tensor_a==random_tensor_b)


tensor([[0.0802, 0.8259, 0.1709, 0.8779],
        [0.2802, 0.3326, 0.0776, 0.5542],
        [0.6719, 0.6149, 0.7984, 0.4920]])
tensor([[0.1696, 0.9631, 0.1609, 0.5392],
        [0.0029, 0.0530, 0.7443, 0.5060],
        [0.1908, 0.1075, 0.8976, 0.7894]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [48]:
#let's  make some random but reproducable tensor

#set the random seed
RANDOM_SEEED=42
torch.manual_seed(RANDOM_SEEED)
random_tensor_c=torch.rand(3,4)

torch.manual_seed(RANDOM_SEEED)
random_tensor_d=torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)

print(random_tensor_c==random_tensor_d)



tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


#Running  tensor and pytorch on the GPU (and making faster computation)

GPU=faster computation on numbers ,thanks to CUDA hardware +PyTorch working behind the seans make everything hunky gody(good)

##chech fpr GPU access with pytorch

In [1]:
#chexk for GPU access with pyTorch
import torch



In [4]:
device="cuda" if torch .cuda.is_available() else "cpu"
device

'cuda'

In [3]:
torch.cuda.device_count()

1

##Putting Tensors(and models )On the GPU
The reason we want our tensors/models on the GPU is because using a gpy result in faster computatiomn

In [5]:
#Createa tensor (defult on the CPU)
tensor =torch.tensor([1,2,3])


#Tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
#Move tensor to GPU (if available)
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

###Moving tensors back to the CPU


In [7]:
#if tensor is on gpu ,can't trankform it to NumPay
tensor_on_gpu.numpy()



TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [8]:
#to fix theCPU tensor with Numpy  issue  ,we can first set it to the cpu
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [9]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

##Exercise and Extra-s