<a href="https://colab.research.google.com/github/lalitbhattarai/Pytorch_Fundamentals/blob/main/Pytorch_Fundamentals_class_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Finding the min,Max,Mean,Sum,etc(Tensor aggregation)

In [ ]:
import torch

In [ ]:
#Create a tensor
x=torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
#find the min
torch.min(x),x.min()


(tensor(0), tensor(0))

In [ ]:
#find the max
torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
#Find the mean In the tensors -Torch.mean requires that is dtype of flaot32
torch.mean(x.type(torch.float32))



tensor(45.)

In [ ]:
y=x.type(torch.float32).mean()
y


tensor(45.)

In [ ]:
y.dtype

torch.float32

In [ ]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

##Finding the positional min and max

In [ ]:
#minding the minumun valu eand its index
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
#this is finding the index of maximum number availablein the tensor and its value
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

Reshaping,staking ,squezzing,and unsquezzing tensor
*Reshaping--Reshape an input tensor to a define ShapeType
*View--return  a view of an input of certaing shape but  keep the same meanory as
the orginal
**Staking--combaining multiple tensors on top of eah oher (vstack )and side by side hstack
**Squeeze--remove all the  1 dimension from the tensor
**unsqueeze--add a 1 dimensions dfrom a tensor
**permute--Return a view of the input with dimension (swapped )in a certain way

In [ ]:
#let's Create a tensor
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#add an extra deminsion
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.size()

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Change the view
z=x.view(1,9)
z,z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#changing Z changes x(Because a view of the tensor share the same memory as the original tensor)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#stack tensor in top of each other
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked


tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
#Torch.squeeze-to remaove the single dims form target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_squeeze=x_reshaped.squeeze()
x_squeeze

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
#Torch.unsqueeze-add the single dime to a target tensor at the specific dims
print(f"Previous target: {x_squeeze}")
print(f"Previous shape: {x_squeeze.shape}")
#Adding an extra dimension with unsqueeze
x_unsqueezed=x_squeeze.unsqueeze(dim=0)
print(f"\n New Tensor: {x_unsqueezed}")
print(f"new Shape:{x_unsqueezed.shape}")



Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

 New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
new Shape:torch.Size([1, 9])


In [ ]:
#trrch.permute-rearrange the dimension of the target random numbers
x_original=torch.rand(size=(224,224,3))  #(height,width,colour_channels(red green and blue))
#premute the original tensor to rearrang the axis (or dim) order.
x_permuted=x_original.permute(2,0,1) #shifts axis 0->1,1->2,2->0
print(f"Previous shape: {x_original.shape}")
print(f"Premuted shape: {x_permuted.shape}")# 9colour channel,height,width

Previous shape: torch.Size([224, 224, 3])
Premuted shape: torch.Size([3, 224, 224])


In [ ]:
x_original[1,0,0]=9.1234

In [ ]:
x_original[1,0,0],x_permuted[1,0,0]

(tensor(9.1234), tensor(9.1234))

##Indexing (select data from tensor)

Indexing with pytorch is similar to indexing with numpy

In [ ]:
#create a tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#Let's index the middle bracket(dim=1)
x[0,0]

tensor([1, 2, 3])

In [ ]:
#let's index on he most inner bracket(last dimension)
x[0,2,2]

tensor(9)

In [ ]:
#you can also use ":" to select "all" os a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
#Get all values of 0th and 1st deminsion but the index 1 nad 2 deiension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:,1,1]

tensor([5])

In [ ]:
#get index of 0 dimension and 1st dimension and all values od 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
#index on x return 9
x[:,2,2]

tensor([9])

In [ ]:
#index on x return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

from ctypes import LibraryLoader
##Pytorch tensors and NumPy
NumPy is a popular scientific Python numeric computing computing LibraryLoader

And because of this .pytorch has functionality to ineract with it

*Dtata is NumPy  ,want in Pytorch tensor->`torch.from_numpy(ndarray)

.Pytorch Tesor ->NumPy ->torch.tensor.numpy()

In [ ]:
#NumPy array to tensor
import torch
import numpy as np

array=np.arange(1.0 ,8.0)
tensor=torch.from_numpy(array) #when you convert the numpy datatype to pytorch datatype the dtype is numpay defult that is float 64
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype

torch.float64

In [ ]:
#change the value of the array
array=array+1
array,tensor


(array([ 4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Tensor to Numpy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

##Dtae :02/03/2025